spring.application.name=restaurant
spring.datasource.url=jdbc:postgresql://localhost:5433/restaurant_db
spring.datasource.username=restaurant_user
spring.datasource.password=restaurant_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
